### ISSUE TITLE
Mono Repo Issue

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/typescript-theme-ui-link#1]
I have had Storybook in mono repos throw errors when trying to use `<Link />` from `gatsby` with TypeScript but this seems to work ok.

[MrLinky](https://github.com/PaulieScanlon/typescript-theme-ui-link/blob/master/src/components/MrLinky/MrLinky.tsx) is a  `<Link />` from `gatsby` but because i'm using the JSX pragma i can pass on the sx prop and style it the way i would as if it were a `<Link />` from `theme-ui`

I've broadly followed the webpack config as outlined in [Docs/visual testing with storybook updates #21378](https://github.com/gatsbyjs/gatsby/pull/21378) but have added some additional loaders for TypeScript and a cheeky little filter for `react-docgen-typescript-loader` so that inherited props that come from extending interfaces aren't surfaced in the PropTable in Storybook

You can see that in `.storybook/main.js`

But...

I think there's something funky going on when this setup is part of a mono repo. I think it might be related to 👇

```javascript
    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/];
```

and i wonder if when using yarn workspaces the `node_modules` aren't where you think they are.

**Comment by PaulieScanlon** [comment]
Ahoy! @ekwuno so next steps will be to see what happens when i try and set this up in a yarn workspace... perhaps i'll do that on another branch... but does [MrLink](https://github.com/PaulieScanlon/typescript-theme-ui-link/blob/master/src/components/MrLinky/MrLinky.tsx) look about right... i think it still pretty much works as a `<Link />` from `gatsby` would and i think all the same props are there, `isCurrent` etc... what do you think?

**Comment by PaulieScanlon** [comment]
@Ekwuno Yeap, sure enough. When this is running in workspace i get the `<Link />` errors when spinning up Storybook

See branch [feat/yarn-workspace](https://github.com/PaulieScanlon/typescript-theme-ui-link/tree/feat/yarn-workspace)


```javascript
ERROR in ../node_modules/gatsby/cache-dir/gatsby-browser-entry.js 25:4
Module parse failed: Unexpected token (25:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   return (
>     <React.Fragment>
|       {finalData && render(finalData)}
|       {!finalData && <div>Loading (StaticQuery)</div>}
 @ ./src/components/MrLinky/MrLinky.tsx 6:0-30 14:13-17
 @ ./src/components/MrLinky/index.ts
 @ ./src/components/MrLinky/MrLinky.stories.tsx
 @ ./src sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.tsx\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ../node_modules/@storybook/core/dist/server/common/polyfills.js ../node_modules/@storybook/core/dist/server/preview/globals.js ../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/preview.js ./.storybook/generated-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by ghengeveld** [comment]
@ndelangen could you take a look?

**Comment by ndelangen** [comment]
How about instead of trying to change the standard loader so much, try to add an extra one that does exactly what you want it to do to `/node_modules/gatsby` only?

**Comment by PaulieScanlon** [comment]
Hey @ndelangen thanks for looking at this. That’s an interesting angle. This webpack config came from the Gatsby docs but they don’t cover the yarn workspace scenario. That said I’m not sure if this is a Gatsby problem. Sounds like what your suggesting is just straight up webpack stuff and it’s sounding like this is neither the responsibility of Storybook or Gatsby but rather a unique problem with Yarn workspaces.... 

I’m gonna have to learn webpack now aren’t I! 😔

**Comment by ndelangen** [comment]
@PaulieScanlon the problem is:

storybook expects all node_modules to be ES5
+
gatsby has JSX in their dist

JSX is not valid javascript, and so you get a syntax error.

---

A webpack loader turns that invalid JS (JSX) into valid JS.

**Comment by PaulieScanlon** [comment]
@ndelangen thanks again mate! Very helpful. I've been putting off learning webpack for too long but now it seems like something i'm just gonna have to suck up! i'm totally in to solving this problem because i know others have experienced it and it would be nice to have Gatsby and Storybook playing well together as they are both super brill brills!

**Comment by PaulieScanlon** [comment]
@ndelangen Not sure if what i've done is good or bad but it works. 

I have two different sets of loaders, one for `.js` and one for `tsx` I guess if this were used in a repo that uses only one or the other one could be removed but for now i'm going to leave it as i've referenced it in the above Gatsby documentation comments. 

[main.js](https://github.com/PaulieScanlon/typescript-theme-ui-link/blob/master/demo/.storybook/main.js)
